import "../../callback-CpIFpq3_.js";
import "../../error-D0foBB4e.js";
import "../../types-FBMSiw9W.js";
import "../../promise-DVfFbAlR.js";
import "../../proxy-DDf0OBup.js";
import "../../react-navigation-CSMv1yLA.js";
import "../../native-CVD6eq_A.js";
import "../../index-BpPUM9Sc.js";
import "../../main_tabs_v2-Zeuz7W44.js";
import { FormSwitch } from "../../FormSwitch-DtChmE8J.js";
export { FormSwitch as default };