import "../../callback-CpIFpq3_.js";
import "../../error-D0foBB4e.js";
import "../../types-UvuTPXDD.js";
import "../../promise-DVfFbAlR.js";
import "../../proxy-DDf0OBup.js";
import "../../react-navigation-yw7PEll6.js";
import "../../native-CIlY-M-l.js";
import "../../index-C7nrTgKF.js";
import "../../main_tabs_v2-5n8vsUP3.js";
import { FormSwitch } from "../../FormSwitch-uMH5s8mz.js";
export { FormSwitch as default };