import "../../callback-CpIFpq3_.js";
import "../../error-D0foBB4e.js";
import "../../types-BPYGQFpF.js";
import "../../promise-DVfFbAlR.js";
import "../../proxy-BpNB6oQJ.js";
import "../../react-navigation-DfGB4RR1.js";
import "../../native-DxwPf9li.js";
import "../../index-DNiry_Zd.js";
import "../../main_tabs_v2-DkAXyEc0.js";
import { FormSwitch } from "../../FormSwitch-_uGiYCtO.js";
export { FormSwitch as default };