import "../../callback-CpIFpq3_.js";
import "../../error-D0foBB4e.js";
import "../../types-Bg9fFOmx.js";
import "../../promise-DVfFbAlR.js";
import "../../proxy-BpNB6oQJ.js";
import "../../react-navigation-yw7PEll6.js";
import "../../native-CIlY-M-l.js";
import { Design, FormSwitch } from "../../index-DE2r-wBx.js";
import "../../main_tabs_v2-5n8vsUP3.js";
export { Design, FormSwitch };