import "../../callback-DNr1bYVq.js";
import "../../error-DWG2BlZz.js";
import "../../types-Q9nY_LVo.js";
import "../../promise-Du5Pcai3.js";
import "../../proxy-KNbRcH7H.js";
import "../../react-navigation-BsoHQk3U.js";
import "../../native-BXtyFZ8I.js";
import { S as FormSwitch, x as Design } from "../../index-CphpZo9T.js";
import "../../main_tabs_v2-DHNkP9c9.js";
export { Design, FormSwitch };