import "../../callback-DNr1bYVq.js";
import "../../error-DWG2BlZz.js";
import "../../types-DW6-O3QH.js";
import "../../promise-Du5Pcai3.js";
import "../../proxy-KNbRcH7H.js";
import "../../utils-CrrdZoS3.js";
import "../../types-B3fMYLLv.js";
import "../../index-f-lJ1t9D.js";
import "../../index-8QuIENve.js";
import "../../constants-Du6Y7hwa.js";
import { _ as UnscopedPluginApi, a as PluginApiExtensionsOptions, c as PluginCleanupApi, d as PluginLifecycles, f as PluginManifest, g as UnscopedInitPluginApi, h as PreInitPluginApi, i as PluginApiDecorator, l as PluginDecorateApi, m as PluginSettingsComponent, n as Plugin, o as PluginApiInLifecycleMap, p as PluginOptions, r as PluginApi, s as PluginCleanup, t as InitPluginApi, u as PluginDependency, v as UnscopedPreInitPluginApi } from "../../types-uXfd5UM3.js";
import "../../index-CaMxvy6S.js";
import "../../index-Bxhv5itw.js";
import "../../index-Di-Mayfc.js";
export { InitPluginApi, Plugin, PluginApi, PluginApiDecorator, PluginApiExtensionsOptions, PluginApiInLifecycleMap, PluginCleanup, PluginCleanupApi, PluginDecorateApi, PluginDependency, PluginLifecycles, PluginManifest, PluginOptions, PluginSettingsComponent, PreInitPluginApi, UnscopedInitPluginApi, UnscopedPluginApi, UnscopedPreInitPluginApi };